---
title: "BSC 6926 B52 Fall 2024"
format: html
---

#### BSC 6926 B52: R workshop on population and community ecological modeling

This is the course website for the R workshop that coincides with PCB 5423 (Advanced Ecology). This website will have the Quarto markdown lessons for each workshop. Find the course schedule and Syllabus [here](sylb.html). This course will be based in R and information about downloading R and Rstudio can be found [here](comp.html).

### Class Resources

-   [Zoom link](https://fiu.zoom.us/j/94001884298?pwd=b25VZTh6eHFlOVdjRDhrbUV6OTBVZz09)
-   [Github repository](https://github.com/SeascapeEcologyLab-workshops/BSC6926-B52_Fall2024)
-   Textbook for R exercises (S) Stevens, M.H.H. 2010. A primer of ecology with R. ISBN 978-0-387-89881-0 (Electronically available at FIU Library) [E-book version](https://hankstevens.github.io/Primer-of-Ecology/)

### R Resources

-   R for Data Science by Hadley Wickham and Garret Grolemund -- An introduction to programming with R: <https://r4ds.hadley.nz/>\
-   Quick-R by datacamp: Quick overview on R programming and statistical approaches. There are more tutorials, but you will be required to register\
-   RStudio Cloud Training Exercises: <https://rstudio.cloud/learn/primers>\
-   Virtual Ecology Portal/EcoVirtual R Package: Website that provides various examples of population and community models that will be discussed in class and the workshop. There is also an R package (EcoVirtual) you can use to run various models included on this website: <http://ecovirtual.ib.usp.br/doku.php?id=start>\
-   ModernDive: Introductory book on R and statistical inference: <https://moderndive.com/index.html>
-   Rstudio: learn R <https://education.rstudio.com/learn/beginner/>
